# .readthedocs.yml
# Read the Docs configuration file
# See  https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - libopenmpi-dev

  # Optionally declare the Python requirements required to build your docs
  jobs:
    pre_install:
      # Needed because scarlet requires pybind11 to build
      - pip install pybind11 wheel
    
    install:
      - pip install -r docs/requirements.txt
      
      # install with no builds to ensure pybind11 is used
      - pip install --no-build-isolation .


# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

